### PR TITLE
hook in project UI to smartsheet loaded data

### PR DESCRIPTION
**Pull request by nick-brady**
@ldnelso2 

I realize I jumped the gun a bit making the whole add + delete bit. Writing to and from smartsheet is not a good near term goal. Would take too much dev. For now, I took the UI, disabled the create/delete, and hooked in into the data loaded with smartsheet. Here is a full page screenshot of the voila rendering.

### CODE REVIEW

**Comment by ldnelso2** [comment]
Super awesome looking!   I can’t wait to take a deeper dive on it but it looks great.  I agree that we shouldn’t write to smartsheet.  It is better as an input tool and it will keep the model clean to abstract the raw inputs to the model.  What often happens with financial models is that people start tweaking everything to “game” the final numbers and then eventually the spreadsheet gets all jacked up and its hard to maintain.  This way, the inputs and comments  are captured clean and then any fudging / tweaking of the output numbers can be kept separate and perhaps in some version control or whatever.

**Comment by nick-brady** [comment]
updated the screenshot.. I realized a graphing function I made to summarize all of the projects wasn't there. tore through my branches and eventually found it. I'm not sure how that ever got left out... worries me lol. Anyways.. won't touch it again 🙅‍♂ until we chat 😬 promise 👍 .

haha

**Comment by ldnelso2** [comment]
Pretty awesome overall... looking a little more closely on my desktop.

I dialed back in some of the assumptions from frontsight.  I also missed something on the cost line (there was 0.25 FTE from digital team that was accounted for, but also 1 FTE from sales that I forgot to include).  anyway, smartsheet is updated.  

ha!  funny, when you look at the math, Frontsight is really a nice winner for them... our assumptions could be wrong, will learn more from patrick tomorrow.  But makes sense, easy to implement and focused on something simple that gets them moving.

**Comment by ldnelso2** [comment]
LMK if you see what is up with the aws jupyterhub server.

**Comment by nick-brady** [comment]
FYI - discount rate still not being used

**Comment by nick-brady** [comment]
I lied, discount rate is being used  😂

**Comment by ldnelso2** [comment]
Sweet!  Looking forward to digging into it

**Pull request merged**
